// src/giantapp-wallpaper-ui-3_0/src/components/side-menu/index.tsx
"use client";

import { useState } from "react";
import NavMenuItem from "./nav-menu-item";
import { CogIcon, HomeIcon, Squares2X2Icon } from "@heroicons/react/24/outline";
import {
    CogIcon as solidCogIcon,
    HomeIcon as solidHomeIcon,
    Squares2X2Icon as solidSquares2X2Icon,
    QuestionMarkCircleIcon as questionMarkCircleIcon
} from "@heroicons/react/24/solid";
import { usePathname } from "next/navigation";
import { useAtomValue } from "jotai";
import { langDictAtom } from "@/atoms/lang";

export default function SideMenu({ lang }: { lang: string }) {
    const dictionary = useAtomValue(langDictAtom);
    const [sidebarTopNavigation] = useState([
        {
            name: dictionary['common'].local,
            href: `/${lang}`,
            urls: [`/${lang}`, `/${lang}.html`],
            icon: HomeIcon,
            selectedIcon: solidHomeIcon,
            current: false,
        },
        // {
        //   name: "旧社区",
        //   href: "/hub-old",
        //   icon: Squares2X2Icon,
        //   selectedIcon: solidSquares2X2Icon,
        //   current: false,
        // },
        {
            name: dictionary['common'].hub,
            href: `/${lang}/hub`,
            urls: [`/${lang}/hub`, `/${lang}/hub.html`],
            icon: Squares2X2Icon,
            selectedIcon: solidSquares2X2Icon,
            current: false,
        },
    ]);

    const [sidebarBottomNavigation] = useState([
        {
            name: dictionary['common'].settings,
            href: `/${lang}/settings`,
            urls: [`/${lang}/settings`, `/${lang}/settings.html`],
            icon: CogIcon,
            selectedIcon: solidCogIcon,
            current: false,
        },
        {
            name: dictionary['common'].about,
            href: `/${lang}/about`,
            urls: [`/${lang}/about`, `/${lang}/about.html`],
            icon: questionMarkCircleIcon,
            selectedIcon: questionMarkCircleIcon,
            current: false,
        },
    ]);
    const pathname = usePathname();
    //更新current
    sidebarTopNavigation.forEach((item) => {
        item.current = item.urls.includes(pathname)
        // console.log("test", item.urls, pathname, item.current);
    });

    sidebarBottomNavigation.forEach((item) => {
        item.current = pathname === item.href
        if (item.href === `/${lang}/settings`) {
            item.current = pathname.startsWith(`/${lang}/settings`) || item.urls.includes(pathname)
        }
    });

    return (
        <>
            <div className="flex w-[68px] overflow-y-auto overflow-x-clip">
                <div className="flex flex-1 w-full flex-col items-center">
                    <div className="w-full flex-1 space-y-1 px-1">
                        {sidebarTopNavigation.map((item) => (
                            <NavMenuItem
                                key={item.name}
                                href={item.href}
                                name={item.name}
                                icon={item.icon}
                                selectedIcon={item.selectedIcon}
                                current={item.current}
                            />
                        ))}
                    </div>
                    <div className="w-full px-1 mb-1 space-y-1">
                        {sidebarBottomNavigation.map((item) => (
                            <NavMenuItem
                                key={item.name}
                                href={item.href}
                                name={item.name}
                                icon={item.icon}
                                selected-icon={item.selectedIcon}
                                current={item.current}
                            />
                        ))}
                    </div>
                </div>
            </div>
        </>
    );
}

// src/giantapp-wallpaper-ui/app/components/SideMenu.vue
<script lang="ts" setup>
import { useRoute } from 'vue-router';

const route = useRoute();
const { t } = useI18n()
const sidebarTopNavigation = computed(() => [
    {
        name: t('common.local'),
        href: '/',
        icon: 'i-heroicons-home',
        selectedIcon: 'i-heroicons-home-solid',
        current: route.path === '/',
    },
    {
        name: t('common.hub'),
        href: '/hub',
        icon: 'i-heroicons-star',
        selectedIcon: 'i-heroicons-star-solid',
        current: route.path === '/hub',
    },
]);

const sidebarBottomNavigation = computed(() => [
    {
        name: t('common.settings'),
        href: '/settings',
        icon: 'i-heroicons-cog',
        selectedIcon: 'i-heroicons-cog-solid',
        current: route.path === '/settings',
    },
    {
        name: t('common.about'),
        href: '/about',
        icon: 'i-heroicons-question-mark-circle',
        selectedIcon: 'i-heroicons-question-mark-circle-solid',
        current: route.path === '/about',
    },
]);
</script>

<template>
    <aside class="flex w-[68px] overflow-y-auto overflow-x-clip">
        <div class="flex flex-1 w-full flex-col items-center">
            <div class="w-full flex-1 space-y-1 px-1">
                <NavMenuItem v-for="item in sidebarTopNavigation" :key="item.name" :href="item.href" :name="item.name"
                    :icon="item.icon" :selected-icon="item.selectedIcon" :current="item.current" />
            </div>
            <div class="w-full px-1 mb-1 space-y-1">
                <NavMenuItem v-for="item in sidebarBottomNavigation" :key="item.name" :href="item.href"
                    :name="item.name" :icon="item.icon" :selected-icon="item.selectedIcon" :current="item.current" />
            </div>
        </div>
    </aside>
</template>
