// src/giantapp-wallpaper-ui/src/components/side-menu/index.tsx
"use client";

import { useState } from "react";
import NavMenuItem from "./nav-menu-item";
import { CogIcon, HomeIcon, Squares2X2Icon, QuestionMarkCircleIcon } from "@heroicons/react/24/outline";
import {
    CogIcon as solidCogIcon,
    HomeIcon as solidHomeIcon,
    Squares2X2Icon as solidSquares2X2Icon,
    QuestionMarkCircleIcon as questionMarkCircleIcon
} from "@heroicons/react/24/solid";
import { usePathname } from "next/navigation";

export default function SideMenu({ lang }: { lang: string }) {
    const [sidebarTopNavigation] = useState([
        {
            name: "本地",
            href: `/${lang}/`,
            urls: ["/", "/index.html"],
            icon: HomeIcon,
            selectedIcon: solidHomeIcon,
            current: false,
        },
        // {
        //   name: "旧社区",
        //   href: "/community-old",
        //   icon: Squares2X2Icon,
        //   selectedIcon: solidSquares2X2Icon,
        //   current: false,
        // },
        {
            name: "社区",
            href: `/${lang}/community`,
            urls: ["/community", "/community.html"],
            icon: Squares2X2Icon,
            selectedIcon: solidSquares2X2Icon,
            current: false,
        },
    ]);

    const [sidebarBottomNavigation] = useState([
        {
            name: "设置",
            href: `/${lang}/settings/`,
            urls: ["/settings", "/settings.html"],
            icon: CogIcon,
            selectedIcon: solidCogIcon,
            current: false,
        },
        {
            name: "关于",
            href: `/${lang}/about`,
            urls: ["/about", "/about.html"],
            icon: questionMarkCircleIcon,
            selectedIcon: questionMarkCircleIcon,
            current: false,
        },
    ]);
    const pathname = usePathname();
    //更新current
    sidebarTopNavigation.forEach((item) => {
        item.current = item.urls.includes(pathname)
    });

    sidebarBottomNavigation.forEach((item) => {
        item.current = pathname === item.href
        if (item.href === `${lang}/settings/`) {
            item.current = pathname.startsWith("/settings") || item.urls.includes(pathname)
        }
    });

    return (
        <>
            <div className="flex w-[68px] overflow-y-auto">
                <div className="flex flex-1 w-full flex-col items-center">
                    <div className="w-full flex-1 space-y-1 px-1">
                        {sidebarTopNavigation.map((item) => (
                            <NavMenuItem
                                key={item.name}
                                href={item.href}
                                name={item.name}
                                icon={item.icon}
                                selectedIcon={item.selectedIcon}
                                current={item.current}
                            />
                        ))}
                    </div>
                    <div className="w-full px-1 mb-1 space-y-1">
                        {sidebarBottomNavigation.map((item) => (
                            <NavMenuItem
                                key={item.name}
                                href={item.href}
                                name={item.name}
                                icon={item.icon}
                                selected-icon={item.selectedIcon}
                                current={item.current}
                            />
                        ))}
                    </div>
                </div>
            </div>
        </>
    );
}

// src/giantapp-wallpaper-ui/app/components/SideMenu.vue
<script lang="ts" setup>
import { useRoute } from 'vue-router';

const route = useRoute();

const sidebarTopNavigation = computed(() => [
    {
        name: '本地',
        href: '/',
        icon: 'i-heroicons-home',
        selectedIcon: 'i-heroicons-home-solid',
        current: route.path === '/',
    },
    {
        name: '社区',
        href: '/hub',
        icon: 'i-heroicons-star',
        selectedIcon: 'i-heroicons-star-solid',
        current: route.path === '/hub',
    },
]);

const sidebarBottomNavigation = computed(() => [
    {
        name: '设置',
        href: '/settings',
        icon: 'i-heroicons-cog',
        selectedIcon: 'i-heroicons-cog-solid',
        current: route.path === '/settings',
    },
    {
        name: '关于',
        href: '/about',
        icon: 'i-heroicons-question-mark-circle',
        selectedIcon: 'i-heroicons-question-mark-circle-solid',
        current: route.path === '/about',
    },
]);
</script>

<template>
    <aside class="flex w-[68px] overflow-y-auto overflow-x-clip">
        <div class="flex flex-1 w-full flex-col items-center">
            <div class="w-full flex-1 space-y-1 px-1">
                <NavMenuItem v-for="item in sidebarTopNavigation" :key="item.name" :href="item.href" :name="item.name"
                    :icon="item.icon" :selected-icon="item.selectedIcon" :current="item.current" />
            </div>
            <div class="w-full px-1 mb-1 space-y-1">
                <NavMenuItem v-for="item in sidebarBottomNavigation" :key="item.name" :href="item.href"
                    :name="item.name" :icon="item.icon" :selected-icon="item.selectedIcon" :current="item.current" />
            </div>
        </div>
    </aside>
</template>
